# Generated by Django 4.1.6 on 2023-03-04 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=150)),
                ('form_id', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quetion', models.TextField()),
                ('formid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userforms')),
            ],
        ),
        migrations.CreateModel(
            name='QueationForImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quetion', models.TextField()),
                ('formid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userforms')),
            ],
        ),
        migrations.CreateModel(
            name='Queation_Text_ans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('ans', models.TextField()),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userforms')),
                ('que', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.submissionform')),
            ],
        ),
    ]
